const { existsSync } = require("node:fs");
const { join } = require("node:path");

const envFile = join(__dirname, "..", ".env");
if (existsSync(envFile)) require("node:process").loadEnvFile?.(envFile);

const pool = require("../src/database/pool");

const migrar = async () => {
    const cliente = await pool.connect();
    try {
        await cliente.query("BEGIN");
        await cliente.query(`
            ALTER TABLE smarttrip.viaje
                ALTER COLUMN "FK_transporte_id" DROP NOT NULL,
                ALTER COLUMN presupuesto_usd DROP NOT NULL,
                ADD COLUMN IF NOT EXISTS estado varchar(30) NOT NULL DEFAULT 'borrador';
            ALTER TABLE smarttrip.destino
                ALTER COLUMN latitud DROP NOT NULL,
                ALTER COLUMN longitud DROP NOT NULL;
            ALTER TABLE smarttrip.usuario
                ADD COLUMN IF NOT EXISTS transporte_preferido varchar(20);
            ALTER TABLE smarttrip.itinerario
                ADD COLUMN IF NOT EXISTS detalle_json jsonb;
            CREATE UNIQUE INDEX IF NOT EXISTS usuario_correo_unico_idx
                ON smarttrip.usuario (correo);
            CREATE UNIQUE INDEX IF NOT EXISTS destino_pais_nombre_unico_idx
                ON smarttrip.destino ("FK_pais_id", nombre);
            CREATE UNIQUE INDEX IF NOT EXISTS preferencia_usuario_perfil_unico_idx
                ON smarttrip.preferencia ("FK_usuario_id")
                WHERE "FK_usuario_id" IS NOT NULL AND "FK_viaje_id" IS NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS preferencia_viaje_unico_idx
                ON smarttrip.preferencia ("FK_viaje_id")
                WHERE "FK_viaje_id" IS NOT NULL AND "FK_usuario_id" IS NULL;
            CREATE TABLE IF NOT EXISTS smarttrip.sesion (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FK_usuario_id" bigint NOT NULL REFERENCES smarttrip.usuario(id) ON DELETE CASCADE,
                token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
                vence_en timestamptz NOT NULL,
                creado_en timestamptz NOT NULL DEFAULT now(),
                CHECK (vence_en > creado_en)
            );
        `);
        await cliente.query("COMMIT");
        console.log("Migración de persistencia aplicada al esquema smarttrip.");
    } catch (error) {
        await cliente.query("ROLLBACK");
        throw error;
    } finally {
        cliente.release();
        await pool.end();
    }
};

migrar().catch((error) => {
    console.error("No se pudo actualizar el esquema smarttrip:", error.message);
    process.exitCode = 1;
});
